Repository zowe/zlux-server-framework, pull requests merged in 2023-07, with the labels that each got.

#449 Redirect to gateway homepage when possible
  CHANGELOG.md
  lib/index.js
  lib/util.js
  lib/webapp.js
Labels: size/M

#472 Do not do body-auth to apiml unless body has properties.
  plugins/sso-auth/lib/apimlHandler.js
Labels: size/XS

#483 More robust redirect
  lib/webapp.js
Labels: size/S

#488 Bugfix reported on callservice as well as attempt to prevent crash on container, or at least trace the issue
  lib/index.js
  utils/yamlConfig.ts
Labels: size/S

#487 Make proxy error out when there's an error
  CHANGELOG.md
  lib/proxy.js
Labels: size/XS

#490 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#491 Update RC with proxy fix
  CHANGELOG.md
  lib/proxy.js
  package-lock.json
  package.json
Labels: size/XS

#489 Fix where a null got into the resolveRelativePaths and object type detection failed
  lib/util.js
  utils/mergeUtils.js
Labels: size/XS

#492 Sync staging with RC
  lib/index.js
  lib/util.js
  utils/mergeUtils.js
  utils/yamlConfig.ts
Labels: size/S
