Repository zowe/zlux-server-framework, pull requests merged in 2024-01, with the labels that each got.

#521 Fix for detecting whether or not in HA mode
  CHANGELOG.md
  lib/util.js
Labels: size/S

#522 Fixes and enhancements for handling multiple discovery servers
  CHANGELOG.md
  lib/apiml.js
  lib/assets/i18n/log/messages_en.json
  lib/index.js
  lib/webapp.js
  plugins/sso-auth/lib/apimlHandler.js
  plugins/sso-auth/lib/ssoAuth.js
Labels: size/M

#528 Fix gatway gateway typo
  plugins/sso-auth/lib/apimlHandler.js
Labels: size/XS

#530 Update yaml to use new actions for v3
  .github/workflows/build-core.yml
Labels: size/S

#531 Fix type in staging
  plugins/sso-auth/lib/apimlHandler.js
Labels: size/XS
