Repository zowe/zlux-server-framework, pull requests merged in 2024-08, with the labels that each got.

#561 Sync staging with RC
  lib/webserver.js
  test/webapp/websocket/package-lock.json
  test/webapp/websocket/package.json
Labels: size/XS

#563 Update V3 staging
  CHANGELOG.md
  lib/apiml.js
  lib/apimlStorage.ts
  lib/assets/i18n/log/messages_en.json
  lib/auth-manager.js
  lib/index.js
  lib/swagger-catalog.js
  lib/tomcatManager.ts
  lib/translation-utils.js
  lib/unp-constants.js
  lib/util.js
  lib/webapp.js
  lib/webauth.js
  lib/webserver.js
  package-lock.json
  package.json
  plugins/sso-auth/lib/apimlHandler.js
  plugins/sso-auth/lib/ssoAuth.js
  test/webapp/websocket/package-lock.json
  test/webapp/websocket/package.json
  utils/install-app.js
  utils/packaging-utils.js
  utils/yamlConfig.ts
Labels: size/XL

#564 axios and ws packages update
  package-lock.json
  test/webapp/websocket/package-lock.json
Labels: dependencies, size/XS

#566 Update build workflow
  .github/workflows/build-core.yml
Labels: size/XS
