Repository zowe/zlux-server-framework, pull requests merged in 2025-02, with the labels that each got.

#589 Fix /server/environment endpoint for best ZSS route (v2)
  CHANGELOG.md
  lib/webapp.js
Labels: size/S

#581 Fix Eureka Registration when ATTLS (v2)
  CHANGELOG.md
  lib/apiml.js
Labels: size/M

#591 Add option to trace eureka registration
  CHANGELOG.md
  lib/apiml.js
  lib/index.js
Labels: size/S

#590 Upgrade actions cache
  .github/workflows/build-core.yml
Labels: size/XS

#592 Add option to trace eureka registration in v3
  CHANGELOG.md
  lib/apiml.js
  lib/index.js
Labels: size/S
