Repository zowe/zlux-server-framework, pull requests merged in 2025-01, with the labels that each got.

#579 Update express (updates send as well)
  package-lock.json
  package.json
Labels: size/XS

#580 Fix Eureka Registration when ATTLS (v3)
  CHANGELOG.md
  lib/apiml.js
Labels: size/S

#576 v3 Bump axios 1.7.7 to 1.7.9
  package-lock.json
  package.json
  test/webapp/websocket/package-lock.json
  test/webapp/websocket/package.json
Labels: size/XS

#575 v2 Bump axios 1.7.7 to 1.7.9
  package-lock.json
  package.json
  test/webapp/websocket/package-lock.json
  test/webapp/websocket/package.json
Labels: size/XS

#583 Use gateway client attls status in eureka object to determine http vs…
  lib/apiml.js
Labels: size/S

#587 Upgrade @rocketsoftware/express-ws and ws
  package-lock.json
  package.json
Labels: size/XS

#588 Fix /server/environment endpoint for best ZSS route (v3)
  CHANGELOG.md
  lib/webapp.js
Labels: bug, size/S
